name: dbt_synthea
version: 1.0.0
config-version: 2

profile: dbt_synthea

model-paths:
  - models
macro-paths:
  - macros
seed-paths:
  - data

models:
  dbt_synthea:
    +materialized: table
    staging:
      +schema: stg
      +materialized: table
      +tags: ['core']
    omop:
      +schema: cdm
      +materialized: table
      +tags: ['core']

seeds:
  dbt_synthea:
    +insert_batch_size: 25
    synthea:
      +column_types:
        CODE: TEXT
        REASONCODE: TEXT
    vocabularies:
      +schema: cdm
      # no schema due to sqlite
    reference:
      +schema: stg
      # no schema due to sqlite
